name: Manual or on PR merge microCMS update

# Controls when the workflow will run
on:
  pull_request:
    branches: 
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  send-signal-to-repo-B:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: |
        echo Test Workflow run
        
    - name: Manual microCMS update Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: yns-ivan/NTT-9-REPO-B
        event-type: update-microcms
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
